# Cloud Build — BuildTrack (fixed 2026-02-18)
# Builds and deploys both frontend and backend to Cloud Run.
# Run: gcloud builds submit --config=cloudbuild.yaml .

steps:
  # ── BUILD BACKEND ──────────────────────────────────────────
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-backend'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/buildtrack-registry/backend:$SHORT_SHA'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/buildtrack-registry/backend:latest'
      - '-f'
      - 'backend/Dockerfile'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-backend'
    waitFor: ['build-backend']
    args:
      - 'push'
      - '--all-tags'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/buildtrack-registry/backend'

  # ── BUILD FRONTEND ─────────────────────────────────────────
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-frontend'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/buildtrack-registry/frontend:$SHORT_SHA'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/buildtrack-registry/frontend:latest'
      - '--build-arg'
      - 'NEXT_PUBLIC_API_URL=https://buildtrack-backend-buildtrac-app.us-central1.run.app' # UPDATE THIS AFTER FIRST DEPLOY (Step 10 in guide)
      - '-f'
      - 'frontend/Dockerfile'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-frontend'
    waitFor: ['build-frontend']
    args:
      - 'push'
      - '--all-tags'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/buildtrack-registry/frontend'

  # ── DEPLOY BACKEND ─────────────────────────────────────────
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-backend'
    waitFor: ['push-backend']
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'buildtrack-backend'
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/buildtrack-registry/backend:$SHORT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--service-account'
      - 'buildtrack-cloudrun@$PROJECT_ID.iam.gserviceaccount.com'
      - '--set-env-vars'
      - >-
        NODE_ENV=production,PORT=4000,FRONTEND_URL=https://buildtrack-frontend-buildtrac-app.us-central1.run.app,JWT_EXPIRES_IN=15m,JWT_REFRESH_EXPIRES_IN=7d,MAIL_MODE=smtp,COOKIE_SECURE=true,COOKIE_SAME_SITE=none,COOKIE_DOMAIN=.run.app,MICROSOFT_TENANT_ID=common,GOOGLE_REDIRECT_URI=https://buildtrack-backend-buildtrac-app.us-central1.run.app/api/auth/oauth/google/callback,MICROSOFT_REDIRECT_URI=https://buildtrack-backend-buildtrac-app.us-central1.run.app/api/auth/oauth/microsoft/callback
      - '--set-secrets'
      - >-
        DATABASE_URL=buildtrack-database-url:latest,JWT_SECRET=buildtrack-jwt-secret:latest,JWT_REFRESH_SECRET=buildtrack-jwt-refresh-secret:latest,GOOGLE_CLIENT_ID=buildtrack-google-client-id:latest,GOOGLE_CLIENT_SECRET=buildtrack-google-client-secret:latest,MICROSOFT_CLIENT_ID=buildtrack-microsoft-client-id:latest,MICROSOFT_CLIENT_SECRET=buildtrack-microsoft-client-secret:latest,SMTP_HOST=buildtrack-smtp-host:latest,SMTP_PORT=buildtrack-smtp-port:latest,SMTP_USER=buildtrack-smtp-user:latest,SMTP_PASS=buildtrack-smtp-password:latest,SMTP_FROM=buildtrack-smtp-from:latest
      - '--add-cloudsql-instances'
      - '$PROJECT_ID:us-central1:buildtrack-db'
      - '--allow-unauthenticated'
      - '--port'
      - '4000'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--timeout'
      - '60s'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'

  # ── DEPLOY FRONTEND ────────────────────────────────────────
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-frontend'
    waitFor: ['push-frontend']
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'buildtrack-frontend'
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/buildtrack-registry/frontend:$SHORT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--service-account'
      - 'buildtrack-cloudrun@$PROJECT_ID.iam.gserviceaccount.com'
      - '--set-env-vars'
      - 'NODE_ENV=production,PORT=3000,BACKEND_URL=https://buildtrack-backend-buildtrac-app.us-central1.run.app'
      - '--allow-unauthenticated'
      - '--port'
      - '3000'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--timeout'
      - '60s'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/buildtrack-registry/backend:$SHORT_SHA'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/buildtrack-registry/backend:latest'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/buildtrack-registry/frontend:$SHORT_SHA'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/buildtrack-registry/frontend:latest'

timeout: '3600s'
