// Auto-generated by scripts/gen-config.js — do not edit manually
// Re-run: npm run gen:config

import configData from "./buildtrack.config.json";

export interface SidebarItem {
  label: string;
  path: string;
  children?: SidebarItem[];
}

export interface NavigationConfig {
  topNav: string[];
  sidebar: SidebarItem[];
}

export interface RoleConfig {
  label: string;
  description: string;
}

export interface ModuleConfig {
  name: string;
  slug: string;
  description: string;
  who: string;
  mvpUser: string;
  process: string;
  screens: string;
  accessRoles: string[];
  fields: string[];
}

export interface BuildTrackConfig {
  navigation: NavigationConfig;
  roles: Record<string, RoleConfig>;
  modules: Record<string, ModuleConfig>;
  moduleOrder: string[];
}

export const config = configData as BuildTrackConfig;
export const navigation = config.navigation;
export const roles = config.roles;
export const modules = config.modules;
export const moduleOrder = config.moduleOrder;

export function getModuleBySlug(slug: string): ModuleConfig | undefined {
  return modules[slug];
}

export function getAllModules(): ModuleConfig[] {
  return moduleOrder.map((slug) => modules[slug]);
}
